lotusd:
  image: sondreb/lotus:latest
  container_name: lotus-main
  ports:
    - "8332:8332"   # RPC mainnet port
    - "8333:8333"   # p2p mainnet port
    - "28332:28332" # ZMQ port
  volumes:
    #- /mnt/data/blockchain-data/lotus-mainnet/lotus-blockchain-data:/data
    #- ../config:/home/bitcoin/config
    - ./blockchain/data:/data
    - ./blockchain/config:/home/bitcoin/config
  restart: unless-stopped
