lotusd:
  build: .
  dockerfile: Dockerfile
  #image: christroutner/bitcoind-bch-abc-0.21.9
  container_name: lotus-testnet
  ports:
    - "11604:11604" # RPC mainnet port
    - "11605:11605" # p2p mainnet port
  volumes:
    - ../../testnet/blockchain-data:/data
    - ../../testnet/config:/home/bitcoin/config
  #restart: always
  #stop_signal: SIGINT
  #stop_signal: SIGTERM #default
  #stop_signal: SIGKILL
  #stop_signal: SIGHUP
