name: Publish Docker Image

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Publish Docker Image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      name: Checkout

    - name: Log Variables
      run: |
        echo "action - ${{ github.event.action }}"
        echo "url - ${{ github.event.release.url }}"
        echo "assets_url - ${{ github.event.release.assets_url }}"
        echo "id - ${{ github.event.release.id }}"
        echo "tag_name - ${{ github.event.release.tag_name }}"
        echo "assets - ${{ github.event.assets }}"
        echo "assets[0] - ${{ github.event.assets[0] }}"

    - name: Build the Docker container image
      working-directory: mainnet
      run: docker build -f "Dockerfile" -t sondreb/lotus:latest -t sondreb/lotus:${{github.event.release.tag_name}} "."

    - name: Login and Push to Docker Registry
      run: |
        docker login -u "sondreb" -p "${{secrets.DockerHubSecret}}"
        docker push --all-tags sondreb/lotus
